source "https://rubygems.org"

# Jekyll and related gems
gem "jekyll", "~> 4.3.0"
gem "jekyll-sass-converter", "~> 3.0"

# Performance and optimization
gem "sassc", "~> 2.4"

# Development dependencies
group :development do
  gem "webrick", "~> 1.7"  # Required for Jekyll serve on Ruby 3.0+
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]